### ISSUE TITLE
Pregunta 3 incorrecta, ¿Solución?

### ISSUE THREAD

**Issue by Leo-Spj** [Leo-Spj/Programacion-Funcional-con-Haskell#1]
https://github.com/Leo-Spj/Programacion-Funcional-con-Haskell/blob/f74af976ec89bf5ab80c511b0cb2d736f106730b/semanas/S5/Pc.hs#L44C1-L51C53

``` haskell
{- 3) Dada una lista, determinar el producto de dicha lista con 
su inversa. Nota: No utilice la funcion haskell reverse.
-}

reversa [] = []
reversa (x:xs) = reversa xs ++ [x]

listaXLista xs = [ x*y | x <- xs , y <- reversa xs ]
```
Obtengo un producto cartesiano, no es lo requerido

**Comment by Brandon-Meneses** [comment]
```haskell
reversa [] = []
reversa (x:xs) = reversa xs ++ [x]

multiplicarListas [] [] = []
multiplicarListas (x:xs) (y:ys) = (x * y) : multiplicarListas xs ys

productoPorInversa lista = multiplicarListas lista (reversa lista)

**Comment by Leo-Spj** [comment]
> ```haskell
> reversa [] = []
> reversa (x:xs) = reversa xs ++ [x]
> 
> multiplicarListas [] [] = []
> multiplicarListas (x:xs) (y:ys) = (x * y) : multiplicarListas xs ys
> 
> productoPorInversa lista = multiplicarListas lista (reversa lista)
> ```

@
